[build]
command = "npm run build:web"
publish = "apps/gajkesari-web/.next"

[build.environment]
NODE_VERSION = "24"
NPM_VERSION = "11"

[[plugins]]
package = "./netlify/plugins/api-proxy"

[[plugins]]
package = "@netlify/plugin-nextjs"
